log:
  consoleLevel: debug
  fileLevel: error
  logFilePath: ""
transfer:
  maxBidiRemoteStreams: 100
  maxIdleTimeout: -1
  keepAlivePeriod: 30000000000
proxy:
  remote:
    - address: localhost
      port: 12306
      tag: p1
  local:
    - address: 127.0.0.1
      port: 8211
      protocol: udp
      remoteTag: p1
      remotePort: 28211