log:
  consoleLevel: debug
  fileLevel: error
  logFilePath: ""
transfer:
  tls:
    crt: ""
    key: ""
  maxBidiRemoteStreams: 100
  maxUniRemoteStreams: 100
  maxStreamReadBufferSize: 1048576
  maxStreamWriteBufferSize: 1048576
  requireAddressValidation: false
  handshakeTimeout: 10000000000
  maxIdleTimeout: 1800000000000
  keepAlivePeriod: 30000000000
role:
  - server
  - client
server:
  listen:
    address: 127.0.0.1
    port: 12306
client:
  conn:
    address: 127.0.0.1
    port: 12306
  proxy:
    services:
      - address: 127.0.0.1
        port: 8211
        protocol: udp
      - address: 127.0.0.1
        port: 8080
        protocol: tcp
      - address: 127.0.0.1
        port: 10003
        protocol: udp