log:
  consoleLevel: debug
  fileLevel: error
  logFilePath: ""
quic:
  maxIdle: -1
  maxIncomeStreams: 100
  keepalive: 20
role:
  - client
client:
  conn:
    address: 127.0.0.1
    port: 12306
  proxy:
    type: reverse
    services:
      - address: 127.0.0.1
        port: 8211
        protocol: udp
      - address: 127.0.0.1
        port: 8080
        protocol: tcp
      - address: 127.0.0.1
        port: 10003
        protocol: udp